//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotifyHotkeys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Hotkey_AddSongToPlaylist1 {
            get {
                return ((bool)(this["Hotkey_AddSongToPlaylist1"]));
            }
            set {
                this["Hotkey_AddSongToPlaylist1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Hotkey_AddSongToPlaylist2 {
            get {
                return ((bool)(this["Hotkey_AddSongToPlaylist2"]));
            }
            set {
                this["Hotkey_AddSongToPlaylist2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Hotkey_AddSongToPlaylist3 {
            get {
                return ((bool)(this["Hotkey_AddSongToPlaylist3"]));
            }
            set {
                this["Hotkey_AddSongToPlaylist3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Hotkey_AddSongToPlaylist4 {
            get {
                return ((bool)(this["Hotkey_AddSongToPlaylist4"]));
            }
            set {
                this["Hotkey_AddSongToPlaylist4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Hotkey_AddSongToPlaylist5 {
            get {
                return ((bool)(this["Hotkey_AddSongToPlaylist5"]));
            }
            set {
                this["Hotkey_AddSongToPlaylist5"] = value;
            }
        }
    }
}
